# Generated by Django 4.2.2 on 2023-06-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'Comment author',
                'verbose_name_plural': 'Comment authors',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page', models.URLField(blank=True, null=True, verbose_name='Home page')),
                ('text', models.TextField(verbose_name='Comment body')),
                ('file', models.FileField(blank=True, null=True, upload_to='comment_files/', verbose_name='Attached comment file')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created datetime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.author', verbose_name='Comment author')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment', verbose_name='Parent comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created'],
            },
        ),
    ]
